[build-system]
build-backend = "poetry.masonry.api"
requires = ["poetry>=0.12"]

[tool]
[tool.poetry]
authors = ["Sam Poder <hi@sampoder.com>"]
description = "ğŸ° Race to the castle with this fun CLI Board Game!"
include = ["kastely/*.py"]
name = "kastely"
version = "0.1.8"
[tool.poetry.dependencies]
Unidecode = "^1.1"
ascii = "^3.6"
colorama = "^0.4.3"
pyfiglet = "^0.8.0"
python = "^3.8"
tabulate = "^0.8.7"
[tool.poetry.dev-dependencies]
[tool.poetry.scripts]
kastely = "kastely.__main__:game"
